### ISSUE TITLE
Error when using example

### ISSUE THREAD

**Issue by Goradiar** [kujosHeist/tle2czml#1]
Hi Shane,

I'm new to github so bare with me if I posted something in an unusual way.  When I execute my python script with your example code and example .txt file with the TLE contents, I get the following error below:
I very much would like to use your code project - thank you for your hard work and for contributing!

2019-01-22T05:28:16.168000+00:00/2019-01-23T05:28:16.168000+00:00
2019-01-22T05:28:16.168000+00:00
()
('Satellite Name: ', 'ISS (ZARYA)')
('TLE Epoch: ', datetime.datetime(2018, 2, 15, 13, 23, 46, 51295))
('Orbit time in Minutes: ', 92.65836501766822)
()
Traceback (most recent call last):
  File "TLEtrans.py", line 5, in <module>
    tle2czml.create_czml("Iridium.txt")
  File "C:\Python27\lib\site-packages\tle2czml\tle2czml.py", line 293, in create_czml
    sat_packet = create_satellite_packet(sat.sat_name, sat.tle_object, sat.orbital_time_in_minutes, start_time, end_time, sat.rgba)
  File "C:\Python27\lib\site-packages\tle2czml\tle2czml.py", line 93, in create_satellite_packet
    packet.path = create_path(availability, orbit_time_in_minutes, rgba)
  File "C:\Python27\lib\site-packages\tle2czml\tle2czml.py", line 144, in create_path
    for i in range(0, number_of_full_orbits + 1):
TypeError: range() integer end argument expected, got float.

**Comment by Goradiar** [comment]
I went into the tle2czml.py code and fixed it by adding the following before the for loop:

number_of_full_orbits = int(number_of_full_orbits)
for i in range(0, number_of_full_orbits + 1):

**Comment by kujosHeist** [comment]
Hi Goradiar, 

Thanks for the message!

I think its because you're using python2.7 instead of python3, because math.floor returns a float in python2, which causes the error, while it returns an int in python3.

If you don't want to update to python3, then your fix should work fine!

All the best,

Shane
