### ISSUE TITLE
Satellite track changes beyond 24 hours.

### ISSUE THREAD

**Issue by CU-Joel** [kujosHeist/tle2czml#2]
Hello Shane,

I am using the tle2czml creator to display multiple satellites over days. When you set the end time greater than 24 hours beyond the start time and then view the satellite orbit in the period past the first 24 hours, the satellite track changes from a single line to multiple lines. Do you know why this is and how I could keep the track as one line?

Thanks
Joel

**Comment by kujosHeist** [comment]
HI CU-Joel,

Sorry for delay!

Just pushed a fix for this issue, so it now should show the correct track for the entire orbit.

I haven't yet updated the package on pypi but I'll do that in few days,

Cheers,

Shane

**Comment by kujosHeist** [comment]
Fixed
